### ISSUE TITLE
Animations labels don't show on mobile

### ISSUE THREAD

**Issue by DeepSpace2** [aatishb/maskmath#13]
![Screenshot_20200912-200844](https://user-images.githubusercontent.com/6841988/93000985-692eca00-f534-11ea-911e-ae8a7ed12f0b.jpg)

**Comment by DeepSpace2** [comment]
Also test on PC by resizing the Chrome window. For some reason `display: none` is applied:

![image](https://user-images.githubusercontent.com/6841988/93004154-10b7f680-f54d-11ea-91b6-15e0e4304fbc.png)

**Comment by aatishb** [comment]
Hi, I actually intended for this behavior, here's the [corresponding line](https://github.com/aatishb/maskmath/blob/master/css/style.css#L371-L373). The issue is at narrow screen width the mask visualization becomes unclear (particularly with one or two masks present). Since the labels are slightly redundant, I opted to remove them at low screen width to make more space for the visualization.
